# Netlify configuratiebestand voor Staalmaatje

# Basis bouwinstellingen
# Hiermee vertellen we Netlify dat dit een simpele site is zonder bouwstap.
[build]
  command = ""
  publish = "/"

# Configuratie voor de Netlify Functions
# Dit vertelt Netlify waar de server-code staat en geeft het meer tijd.
[functions]
  directory = "netlify/functions"
  timeout = 25

