# Netlify configuratiebestand voor Staalmaatje

# Basis bouwinstellingen
[build]
  # Vertel Netlify dat er geen build-commando is voor de site.
  # De dependencies in package.json worden wel geïnstalleerd voor de functies.
  command = ""
  # De bestanden voor de website staan in de hoofdmap.
  publish = "/"

# Configuratie voor de Netlify Functions
[functions]
  # Specificeer expliciet waar de functies staan.
  directory = "netlify/functions"
  # Verhoog de standaard time-out voor de functies.
  timeout = 25

